# brew bundle install --file=~/Brewfile [--cleanup]


brew "ag"
brew "difftastic"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "golang"
brew "htop"
brew "jq"
brew "neovim"
brew "parallel"
brew "qemu"
brew "ripgrep"
brew "sd"
brew "tokei"
brew "xsv"

cask "firefox"
cask "kitty"
cask "wine-stable", args: { no_quarantine: true }

# Ory
tap "cockroachdb/tap"
tap "microsoft/git"

brew "cockroach"
brew "coreutils"
brew "delve"
brew "gh"
brew "go-jsonnet"
brew "graphviz"
brew "grype"
brew "k9s"
brew "kubectl"
brew "markdownlint-cli"
brew "microsoft-git"
brew "mysql-client@8.0"
brew "npm"
brew "openjdk@11"
brew "pkcs11-tools"
brew "skaffold"
brew "softhsm"
brew "vale"

cask "docker"
cask "google-cloud-sdk"
cask "virtualbox"
